param(
    [string]$Output = ""
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($Output)) {
    $Output = Join-Path $root "os/trust_store.sura"
}

# Every downloaded root is pinned by the SHA-256 fingerprint of its DER
# encoding. A changed response, HTML error page, or silently replaced
# certificate fails before the generated source is touched.
$roots = @(
    [ordered]@{
        Name = "ISRG Root X1"
        Symbol = "isrg_root_x1"
        Url = "https://letsencrypt.org/certs/isrgrootx1.der"
        Format = "der"
        Bytes = 1391
        Sha256 = "96bcec06264976f37460779acf28c5a7cfe8a3c0aae11a8ffcee05c0bddf08c6"
    },
    [ordered]@{
        Name = "DigiCert Global Root G2"
        Symbol = "digicert_global_root_g2"
        Url = "https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem"
        Format = "pem"
        Bytes = 914
        Sha256 = "cb3ccbb76031e5e0138f8dd39a23f9de47ffc35e43c1144cea27d46a5ab1cb5f"
    },
    [ordered]@{
        Name = "GlobalSign Root CA - R3"
        Symbol = "globalsign_root_ca_r3"
        Url = "https://secure.globalsign.com/cacert/root-r3.crt"
        Format = "der"
        Bytes = 867
        Sha256 = "cbb522d7b7f127ad6a0113865bdf1cd4102e7d0759af635a7cf4720dc963c53b"
    },
    [ordered]@{
        Name = "Amazon Root CA 1"
        Symbol = "amazon_root_ca_1"
        Url = "https://www.amazontrust.com/repository/AmazonRootCA1.cer"
        Format = "der"
        Bytes = 837
        Sha256 = "8ecde6884f3d87b1125ba31ac3fcb13d7016de7f57cc904fe1cb97c6ae98196e"
    },
    [ordered]@{
        Name = "USERTrust RSA Certification Authority"
        Symbol = "usertrust_rsa_certification_authority"
        Url = "https://support.sectigo.com/sfc/servlet.shepherd/version/download/0683l00000ENwaH"
        Format = "pem"
        Bytes = 1506
        Sha256 = "e793c9b02fd8aa13e21c31228accb08119643b749c898964b1746d46c3d4cbd2"
    },
    [ordered]@{
        Name = "Microsoft RSA Root Certificate Authority 2017"
        Symbol = "microsoft_rsa_root_ca_2017"
        Url = "https://www.microsoft.com/pkiops/certs/Microsoft%20RSA%20Root%20Certificate%20Authority%202017.crt"
        Format = "der"
        Bytes = 1452
        Sha256 = "c741f70f4b2a8d88bf2e71c14122ef53ef10eba0cfa5e64cfa20f418853073e0"
    }
)

function Convert-PemToDer {
    param([byte[]]$Bytes)
    $text = [System.Text.Encoding]::ASCII.GetString($Bytes)
    $match = [regex]::Match(
        $text,
        "-----BEGIN CERTIFICATE-----\s*(?<body>[A-Za-z0-9+/=\r\n]+?)\s*-----END CERTIFICATE-----"
    )
    if (-not $match.Success) {
        throw "downloaded PEM certificate is malformed"
    }
    $base64 = [regex]::Replace($match.Groups["body"].Value, "\s", "")
    return [Convert]::FromBase64String($base64)
}

$temporaryFiles = New-Object System.Collections.Generic.List[string]
try {
    $generated = New-Object System.Collections.Generic.List[object]
    foreach ($entry in $roots) {
        $temporary = Join-Path (
            [System.IO.Path]::GetTempPath()
        ) ("sura-trust-root-" + [Guid]::NewGuid().ToString("N") + ".crt")
        $temporaryFiles.Add($temporary)
        Invoke-WebRequest -UseBasicParsing -Uri $entry.Url -OutFile $temporary
        [byte[]]$downloaded = [System.IO.File]::ReadAllBytes($temporary)
        [byte[]]$der = if ($entry.Format -eq "pem") {
            Convert-PemToDer $downloaded
        }
        else {
            $downloaded
        }

        $sha256 = [System.Security.Cryptography.SHA256]::Create()
        try {
            [byte[]]$fingerprint = $sha256.ComputeHash($der)
        }
        finally {
            $sha256.Dispose()
        }
        $actualSha256 =
            ([BitConverter]::ToString($fingerprint) -replace "-", "").ToLowerInvariant()
        if ($actualSha256 -ne $entry.Sha256) {
            throw "$($entry.Name) SHA-256 mismatch: expected=$($entry.Sha256) actual=$actualSha256"
        }
        if ($der.Length -ne $entry.Bytes) {
            throw "$($entry.Name) DER length mismatch: expected=$($entry.Bytes) actual=$($der.Length)"
        }
        $generated.Add([pscustomobject]@{
            Entry = $entry
            Der = $der
            Fingerprint = $fingerprint
            ActualSha256 = $actualSha256
        })
    }

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Generated by tools/sura_trust_store_generate.ps1 from pinned")
    $lines.Add("# certificate-authority root certificates. The generator verifies each")
    $lines.Add("# DER length and SHA-256 fingerprint before replacing this file.")
    $lines.Add("")
    foreach ($item in $generated) {
        $symbol = $item.Entry.Symbol
        $byteText = ($item.Der | ForEach-Object { [string]$_ }) -join ", "
        $fingerprintText =
            ($item.Fingerprint | ForEach-Object { [string]$_ }) -join ", "
        $lines.Add("# $($item.Entry.Name)")
        $lines.Add("os_trust_${symbol}_der is static.bytes([$byteText], 1)")
        $lines.Add("os_trust_${symbol}_der_bytes: u64 is $($item.Der.Length)")
        $lines.Add("os_trust_${symbol}_sha256 is static.bytes([$fingerprintText], 1)")
        $lines.Add("")
    }
    $lines.Add("os_trust_root_count: u64 is $($generated.Count)")
    $lines.Add("")
    $lines.Add("func os_trust_root_der(index: u64) do")
    for ($index = 0; $index -lt $generated.Count; $index++) {
        $symbol = $generated[$index].Entry.Symbol
        $lines.Add("  if index == $index then return os_trust_${symbol}_der")
    }
    $lines.Add("  return 0")
    $lines.Add("end")
    $lines.Add("")
    $lines.Add("func os_trust_root_der_bytes(index: u64) do")
    for ($index = 0; $index -lt $generated.Count; $index++) {
        $symbol = $generated[$index].Entry.Symbol
        $lines.Add("  if index == $index then return os_trust_${symbol}_der_bytes")
    }
    $lines.Add("  return 0")
    $lines.Add("end")
    $lines.Add("")
    $lines.Add("func os_trust_root_sha256(index: u64) do")
    for ($index = 0; $index -lt $generated.Count; $index++) {
        $symbol = $generated[$index].Entry.Symbol
        $lines.Add("  if index == $index then return os_trust_${symbol}_sha256")
    }
    $lines.Add("  return 0")
    $lines.Add("end")
    $content = ($lines -join "`n") + "`n"

    $outputPath = [System.IO.Path]::GetFullPath($Output)
    $outputDirectory = [System.IO.Path]::GetDirectoryName($outputPath)
    if (-not [System.IO.Directory]::Exists($outputDirectory)) {
        [System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
    }
    $outputTemporary = Join-Path $outputDirectory (
        [System.IO.Path]::GetFileName($outputPath) +
        "." +
        [Guid]::NewGuid().ToString("N") +
        ".tmp"
    )
    $temporaryFiles.Add($outputTemporary)
    [System.IO.File]::WriteAllText(
        $outputTemporary,
        $content,
        [System.Text.UTF8Encoding]::new($false)
    )
    # The compiler must never observe a partially generated source file.
    # Completing the temporary file in the destination directory and then
    # renaming it keeps each visible trust-store generation whole.
    if ([System.IO.File]::Exists($outputPath)) {
        $outputBackup = Join-Path $outputDirectory (
            [System.IO.Path]::GetFileName($outputPath) +
            "." +
            [Guid]::NewGuid().ToString("N") +
            ".bak"
        )
        $temporaryFiles.Add($outputBackup)
        [System.IO.File]::Replace($outputTemporary, $outputPath, $outputBackup)
        if ([System.IO.File]::Exists($outputBackup)) {
            [System.IO.File]::Delete($outputBackup)
        }
        [void]$temporaryFiles.Remove($outputBackup)
    }
    else {
        [System.IO.File]::Move($outputTemporary, $outputPath)
    }
    [void]$temporaryFiles.Remove($outputTemporary)
    "trust store generated: $outputPath"
    foreach ($item in $generated) {
        "$($item.Entry.Name) SHA-256: $($item.ActualSha256)"
    }
}
finally {
    foreach ($temporary in $temporaryFiles) {
        if (Test-Path -LiteralPath $temporary -PathType Leaf) {
            Remove-Item -LiteralPath $temporary -Force
        }
    }
}
