<#
.SYNOPSIS
    Generate the standard-library reference from the stable API snapshot.

.DESCRIPTION
    `reference.html` is a language guide - syntax, install, compatibility tiers -
    and does not list the library functions. This produces the per-function
    reference instead, and generates it from `tests/compat/<series>/stable-api.json`
    rather than from prose, so it cannot drift from the compatibility contract
    the engine is actually tested against.

    Scope is the point, and the generated document says so. The snapshot covers
    the *stable* surface: 112 symbols across 6 modules at 1.11. The engine's
    builtin table holds several hundred more names that are callable today but
    carry no compatibility guarantee. A reference that silently listed only 112
    would read as "this is the standard library"; one that listed all of them
    would imply a stability promise that does not exist. So this documents the
    contracted surface and states plainly what it is not.

.PARAMETER Snapshot
    Stable API snapshot JSON. Defaults to the series named in compatibility.json.

.PARAMETER Out
    Output Markdown path. Defaults to STDLIB_REFERENCE.md in the repo root.

.EXAMPLE
    .\tools\sura_stdlib_reference.ps1

.EXAMPLE
    .\tools\sura_stdlib_reference.ps1 -Snapshot tests\compat\1.11\stable-api.json -Out docs\stdlib.md
#>
param(
    [string]$Snapshot = "",
    [string]$Out = ""
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path | Split-Path -Parent

# Resolve the snapshot through compatibility.json so this tool follows the
# contract rather than hardcoding a series that will age out.
if (-not $Snapshot) {
    $compatPath = Join-Path $root "compatibility.json"
    if (-not (Test-Path -LiteralPath $compatPath)) {
        Write-Error "compatibility.json not found: $compatPath"
        exit 2
    }
    $compat = Get-Content -LiteralPath $compatPath -Raw -Encoding UTF8 | ConvertFrom-Json
    $rel = $compat.stable_api.snapshot
    if (-not $rel) {
        Write-Error "compatibility.json has no stable_api.snapshot entry."
        exit 2
    }
    $Snapshot = Join-Path $root $rel
}
if (-not $Out) { $Out = Join-Path $root "STDLIB_REFERENCE.md" }

if (-not (Test-Path -LiteralPath $Snapshot)) {
    Write-Error "Stable API snapshot not found: $Snapshot"
    exit 2
}

$snap = Get-Content -LiteralPath $Snapshot -Raw -Encoding UTF8 | ConvertFrom-Json
$snapHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $Snapshot).Hash.ToLower()
$snapRel = $Snapshot.Replace($root, "").TrimStart("\", "/") -replace "\\", "/"

$modules = @($snap.modules)
$symbolTotal = 0
foreach ($m in $modules) { $symbolTotal += @($m.symbols).Count }

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Sura standard library reference")
$lines.Add("")
$lines.Add("Generated by ``tools/sura_stdlib_reference.ps1`` from the stable API")
$lines.Add("snapshot. Do not edit by hand - regenerate instead.")
$lines.Add("")
$lines.Add("| Field | Value |")
$lines.Add("| --- | --- |")
$lines.Add("| Series | $($snap.series) |")
$lines.Add("| Baseline version | $($snap.baseline_version) |")
$lines.Add("| Modules | $($modules.Count) |")
$lines.Add("| Symbols | $symbolTotal |")
$lines.Add("| Source | ``$snapRel`` |")
$lines.Add("| Source SHA-256 | ``$snapHash`` |")
$lines.Add("")
$lines.Add("## What this covers, and what it does not")
$lines.Add("")
$lines.Add("This is the **stable** surface: the functions covered by the")
$lines.Add("compatibility contract in ``compatibility.json``, which promises no")
$lines.Add("removal and no signature change without a deprecation cycle. Those")
$lines.Add("promises are what make this list worth writing down.")
$lines.Add("")
$lines.Add("The engine's builtin table contains several hundred additional names")
$lines.Add("that resolve and run today - aliases, platform helpers, and areas still")
$lines.Add("moving. They are usable, but nothing here guarantees they will keep")
$lines.Add("their name or shape, so they are deliberately absent. **A function's")
$lines.Add("absence from this document means it is uncontracted, not that it is")
$lines.Add("missing from the engine.**")
$lines.Add("")

foreach ($m in ($modules | Sort-Object -Property name)) {
    $syms = @($m.symbols)
    $lines.Add("## ``$($m.name)`` ($($syms.Count))")
    $lines.Add("")
    $lines.Add("| Name | Signature |")
    $lines.Add("| --- | --- |")
    foreach ($s in ($syms | Sort-Object -Property name)) {
        $sig = if ($s.signature) { $s.signature } else { "$($m.name).$($s.name)(...)" }
        $lines.Add("| ``$($s.name)`` | ``$sig`` |")
    }
    $lines.Add("")
}

$lines.Add("## Regenerating")
$lines.Add("")
$lines.Add('```')
$lines.Add(".\tools\sura_stdlib_reference.ps1")
$lines.Add('```')
$lines.Add("")
$lines.Add("The snapshot path is read from ``compatibility.json`` so this follows")
$lines.Add("the contract rather than a hardcoded series. If the numbers above stop")
$lines.Add("matching the snapshot, this file was edited by hand or is stale.")

Set-Content -LiteralPath $Out -Value ($lines -join "`n") -Encoding UTF8

Write-Host ("Wrote {0}" -f $Out)
Write-Host ("  series  : {0} (baseline {1})" -f $snap.series, $snap.baseline_version)
Write-Host ("  modules : {0}" -f $modules.Count)
Write-Host ("  symbols : {0}" -f $symbolTotal)
Write-Host ("  source  : {0}" -f $snapRel)
exit 0
