param(
    [string]$Aot = (Join-Path $PSScriptRoot "sura_aot.ps1"),
    [string]$Engine = (Join-Path (Split-Path -Parent $PSScriptRoot) "SuraLanguage.exe")
)

$ErrorActionPreference = "Stop"
$temp = Join-Path ([System.IO.Path]::GetTempPath()) ("sura_aot_" + [System.Guid]::NewGuid().ToString("N"))
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

try {
    if (-not (Test-Path -LiteralPath $Aot)) {
        throw "AOT helper not found: $Aot"
    }
    if (-not (Test-Path -LiteralPath $Engine)) {
        throw "Sura engine not found: $Engine"
    }

    New-Item -ItemType Directory -Force -Path $temp | Out-Null
    $source = Join-Path $temp "aot_app.sura"
    $bytecode = [System.IO.Path]::ChangeExtension($source, ".sura.bc")
    $launcher = [System.IO.Path]::ChangeExtension($source, ".aot.bat")

    [System.IO.File]::WriteAllText($source, @"
func sum_to(n) do
  total is 0
  for i in 1 to n do
    total += i
  end
  return total
end

print sum_to(5)
"@, $utf8NoBom)

    $aotOutput = & powershell -NoProfile -ExecutionPolicy Bypass -File $Aot -Source $source -Engine $Engine 2>&1 | ForEach-Object { "$_" }
    if ($LASTEXITCODE -ne 0) {
        Write-Output ($aotOutput -join "`n")
        throw "sura_aot failed with exit code $LASTEXITCODE"
    }
    if (-not (Test-Path -LiteralPath $bytecode)) {
        throw "expected bytecode artifact at $bytecode"
    }
    if (-not (Test-Path -LiteralPath $launcher)) {
        throw "expected AOT launcher at $launcher"
    }
    $launcherText = [System.IO.File]::ReadAllText($launcher, [System.Text.Encoding]::ASCII)
    if ($launcherText -notmatch "--load" -or $launcherText -notmatch [regex]::Escape($bytecode)) {
        throw "launcher should load the generated bytecode artifact"
    }

    $loadedOutput = & $Engine --load $bytecode 2>&1 | ForEach-Object { "$_" }
    if ($LASTEXITCODE -ne 0 -or (($loadedOutput -join "`n").Trim() -ne "15")) {
        Write-Output ($loadedOutput -join "`n")
        throw "compiled bytecode did not run with expected output"
    }

    $launcherOutput = & $launcher 2>&1 | ForEach-Object { "$_" }
    if ($LASTEXITCODE -ne 0 -or (($launcherOutput -join "`n").Trim() -ne "15")) {
        Write-Output ($launcherOutput -join "`n")
        throw "AOT launcher did not run with expected output"
    }

    "aot_smoke: PASS"
}
finally {
    Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue
}
