param(
    [string]$Engine = ".\SuraLanguage.exe"
)

$ErrorActionPreference = "Stop"

$EnginePath = (Resolve-Path $Engine).Path
$temp = Join-Path ([System.IO.Path]::GetTempPath()) ("sura_stdlib_modules_" + [System.Guid]::NewGuid().ToString("N"))
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-Text {
    param([string]$Path, [string]$Text)
    $parent = Split-Path -Parent $Path
    if ($parent) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
    $Text = $Text -replace "`r`n", "`n"
    if (-not $Text.EndsWith("`n")) { $Text += "`n" }
    [System.IO.File]::WriteAllText($Path, $Text, $utf8NoBom)
}

function Run-Engine {
    param([string]$Script)
    $old = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    Push-Location $temp
    try {
        $out = & $EnginePath $Script 2>&1 | ForEach-Object { "$_" }
        $code = $LASTEXITCODE
    } finally {
        Pop-Location
        $ErrorActionPreference = $old
    }
    return @{ Code = $code; Output = ($out -join "`n") }
}

try {
    New-Item -ItemType Directory -Force -Path $temp | Out-Null
    $script = Join-Path $temp "stdlib_modules.sura"
    Write-Text $script @'
use regex
use array
use set
use math
use path
use string
use os
use datetime
use crypto
use cli
use log
use console
use json
use dict
use fs
use db
use http
use async
use test
use random
use python
use ffi
use plugin
use vector
use graphics3d
use rag
use tensor
use nn
use ai
use autograd
use stream
use tool
use llm

assert(regex.match("sura-2026", "^sura-\d+$"))
assert_eq(regex.replace("sura-2026", "\d+", "lang"), "sura-lang")
matches is regex.find_all("a1 b22 c333", "\d+")
assert_eq(matches.len(), 3)
pieces is regex.split("red, blue;green", "\s*[,;]\s*")
assert_eq(pieces.len(), 3)
assert_eq(pieces[1], "blue")
assert_eq(regex_split("a  b", "\s+")[1], "b")
literal_pattern is regex.escape("a+b? [x]")
assert(regex.match("a+b? [x]", "^" + literal_pattern + "$"))
assert_eq(regex.find_all("a+b? [x] axb?", literal_pattern).len(), 1)
capture is regex.capture("user=kim score=42", "user=([A-Za-z]+) score=([0-9]+)")
assert_eq(capture[1], "kim")
assert_eq(capture[2], "42")
captures is regex.captures("a=1 b=22", "([a-z])=([0-9]+)")
assert_eq(captures.len(), 2)
assert_eq(captures[1][2], "22")
assert_eq(type(regex.capture("none", "id=([0-9]+)")), "nil")

items is [3, 1, 2]
assert_eq(array.len(items), 3)
assert_eq(array_len(items), 3)
assert_eq(array.length(items), 3)
assert_eq(array_length(items), 3)
assert_eq(array.size(items), 3)
assert_eq(array_size(items), 3)
assert_eq(items.length(), 3)
assert_eq(items.size(), 3)
assert_eq(array.slice(items, 1).len(), 2)
assert_eq(array.contains(items, 1), true)
assert_eq(array.index_of(items, 2), 2)
assert_eq(array.push(items, 4), 4)
assert_eq(array.pop(items), 4)
assert_eq(array.sort(array.clone(items))[0], 1)
assert_eq(array.reverse(array.clone(items))[0], 2)
assert_eq(array.concat([1], [2, 3]).len(), 3)
assert_eq(array.sum([1, 2, 3]), 6)
assert_eq(array.avg([2, 4, 6]), 4)
assert_eq(type(array.avg([])), "nil")
assert_eq(array.min([4, -2, 7]), -2)
assert_eq(array.max([4, -2, 7]), 7)
assert_eq(type(array.min([])), "nil")
assert_eq(type(array.max([])), "nil")
assert_eq(array.unique([1, 1, 2, 2, "x", "x"]).join(","), "1,2,x")
assert_eq(array.flatten([1, [2, [3]], 4], 2).join(","), "1,2,3,4")
flat_once is array_flatten([1, [2, [3]]], 1)
assert_eq(flat_once[2].len(), 1)
assert_eq(array.range(5).join(","), "0,1,2,3,4")
assert_eq(array.range(2, 7, 2).join(","), "2,4,6")
assert_eq(array.range(5, 1, -2).join(","), "5,3")
chunks is array.chunk(["a", "b", "c", "d", "e"], 2)
assert_eq(chunks.len(), 3)
assert_eq(chunks[2][0], "e")
zipped is array.zip(["a", "b"], [1, 2, 3])
assert_eq(zipped.len(), 2)
assert_eq(zipped[1][0], "b")
assert_eq(zipped[1][1], 2)
assert_eq(array_repeat("x", 3).join(""), "xxx")

left_set is ["ai", "game", "ai"]
right_set is ["game", "tool"]
assert_eq(set.union(left_set, right_set).join(","), "ai,game,tool")
assert_eq(set.intersection(left_set, right_set).join(","), "game")
assert_eq(set.difference(left_set, right_set).join(","), "ai")
assert_eq(set.symmetric_difference(left_set, right_set).join(","), "ai,tool")
assert(set.is_subset(["ai"], left_set))
assert(set.is_superset(left_set, ["game"]))
assert_eq(set_union([1, 2, 2], [2, 3]).join(","), "1,2,3")

assert_between(math.pi, 3, 4)
assert_eq(math.floor(math.pi), 3)
assert_eq(math.pow(2, 8), 256)
assert_eq(math.clamp(12, 0, 10), 10)
assert_eq(math.max(3, 9, 1), 9)

assert_eq(path.basename("nested/file.sura"), "file.sura")
assert_eq(path.ext("nested/file.sura"), ".sura")
assert_eq(path.stem("nested/file.sura"), "file")
assert(path.join("nested", "file.sura").contains("file.sura"))
assert(path.abs("note.txt").contains("note.txt"))

assert_eq(string.len("sura"), 4)
assert_eq(string.length("sura"), 4)
assert_eq(string.size("sura"), 4)
assert_eq("sura".length(), 4)
assert_eq("sura".size(), 4)
assert_eq(string_size("sura"), 4)
assert_eq(string.upper("sura"), "SURA")
assert(string.starts_with("sura-language", "sura"))
assert(string.ends_with("sura-language", "language"))
assert_eq(string.join(["ai", "game"], "/"), "ai/game")
assert_eq(string.lines("a\nb\n").join("|"), "a|b")
assert_eq(string.lines("").len(), 0)
assert_eq(string_words("  ai   agent  tools ").join(","), "ai,agent,tools")
assert_eq(string.repeat("ha", 3), "hahaha")
assert_eq(string.pad_left("7", 3, "0"), "007")
assert_eq(string.pad_right("go", 4, "."), "go..")
assert_eq(string.chunks("abcdef", 2)[1], "cd")

os.env_set("SURA_STDLIB_MODULE_SMOKE", "ok")
assert_eq(os.env_get("SURA_STDLIB_MODULE_SMOKE"), "ok")
assert_eq(os.env_require("SURA_STDLIB_MODULE_SMOKE"), "ok")
file_write("module.env", "SURA_STDLIB_MODULE_LOADED=loaded\n")
loaded_env is os.env_load("module.env", true)
assert_eq(loaded_env.SURA_STDLIB_MODULE_LOADED, "loaded")
assert(os.cwd().len() > 0)
assert(os.argc() >= 0)
assert(os.script_name().contains("stdlib_modules.sura"))
assert(os.home_dir().len() > 0)
assert(os.temp_dir().len() > 0)
assert(os.path_separator().len() == 1)
assert(os.name().len() > 0)
assert_eq(type(os.is_windows()), "bool")
assert_eq(home_dir(), os.home_dir())
assert_eq(temp_dir(), os.temp_dir())
assert_eq(path_separator(), os.path_separator())
assert_eq(os_name(), os.name())
assert_eq(is_windows(), os.is_windows())
if os.is_windows() then
  assert(os.cmd_exists("cmd"))
  assert(os.which("cmd").len() > 0)
  assert(cmd_exists("cmd"))
  assert(which("cmd").len() > 0)
else
  assert(os.cmd_exists("sh"))
  assert(os.which("sh").len() > 0)
  assert(cmd_exists("sh"))
  assert(which("sh").len() > 0)
end
assert(not os.cmd_exists("__sura_missing_command_for_smoke__"))
assert(not command_exists("__sura_missing_command_for_smoke__"))
run_result is os.run("echo sura-cmd-run")
assert(run_result.ok)
assert_eq(run_result.exit_code, 0)
assert_eq(run_result.command, "echo sura-cmd-run")
assert(run_result.output.contains("sura-cmd-run"))
direct_run_result is cmd_run("echo sura-cmd-direct")
assert(direct_run_result.ok)
assert(direct_run_result.output.contains("sura-cmd-direct"))
joined_text is "sura joined"
quoted_arg is cmd_quote(joined_text)
assert(quoted_arg.len() > joined_text.len())
joined_cmd is os.cmd_join(["echo", joined_text])
assert(joined_cmd.contains("sura"))
joined_result is cmd_run(joined_cmd)
assert(joined_result.ok)
assert(joined_result.output.contains("sura joined"))
assert_eq(os.cmd_join(["echo", "plain"]), cmd_join(["echo", "plain"]))
checked_result is os.run_checked(cmd_join(["echo", "sura checked"]))
assert(checked_result.ok)
assert_eq(checked_result.exit_code, 0)
assert(checked_result.output.contains("sura checked"))
missing_run_result is cmd_run("__sura_missing_command_for_run__")
assert(not missing_run_result.ok)
assert(missing_run_result.exit_code != 0)
os.wait(1)

ts is datetime.parse("2026-05-16T12:34:56")
parts is datetime.parts(ts)
assert_eq(parts.year, 2026)
tomorrow is datetime.add(ts, 86400)
assert_eq(datetime.diff(tomorrow, ts), 86400)
assert_eq(datetime.utc_format(datetime.add(0, 60), "%H:%M:%S"), "00:01:00")
assert_eq(datetime.utc_format(0, "%Y-%m-%d"), "1970-01-01")

assert_eq(crypto.sha256("abc"), "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")
secure_bytes is crypto.random_bytes(8)
assert_eq(secure_bytes.len(), 8)
assert_between(secure_bytes[0], 0, 255)
secure_hex is crypto.random_hex(16)
assert_eq(secure_hex.len(), 32)
assert_match(secure_hex, "^[0-9a-f]+$")
assert_eq(secure_random_bytes(4).len(), 4)
short_secure_hex is secure_random_hex(4)
assert_eq(short_secure_hex.len(), 8)
assert_match(short_secure_hex, "^[0-9a-f]+$")
assert(crypto.constant_time_eq("token-123", "token-123"))
assert(not crypto.constant_time_eq("token-123", "token-124"))
assert(not constant_time_eq("token", "tokenx"))
assert(crypto_constant_time_eq(hmac_sha256("secret", "body"), hmac_sha256("secret", "body")))
assert(secure_compare("abc", "abc"))
assert(not secure_compare("abc", "abcd"))
assert_eq(crypto.hex_decode(crypto.hex_encode("sura")), "sura")
assert_eq(crypto.base64_decode(crypto.base64_encode("sura")), "sura")
assert_eq(crypto.base64_url_encode("sura"), "c3VyYQ")
assert_eq(crypto.base64_url_decode("c3VyYQ"), "sura")

parsed is cli.parse("--fast --target wasm --tag ai --tag tools --no-cache app.sura", ["target", "tag"])
assert(parsed.fast)
assert_eq(parsed.target, "wasm")
assert_eq(parsed.tag.len(), 2)
assert_eq(parsed.cache, false)
assert_eq(parsed.args[0], "app.sura")

obj is json.parse(json.stringify({ok: true, name: "sura"}))
assert(obj.ok)
assert_eq(json.path(obj, "name"), "sura")
assert(json.has_path(obj, "name"))
assert(not json.has_path(obj, "missing"))
assert(json_has_path({ok:nil}, "ok"))
base_patch_obj is {name: "sura", meta: {score: 1, old: true}, keep: [1]}
merged_patch_obj is json.merge_patch(base_patch_obj, {meta: {score: 2, old: nil}, added: true})
assert_eq(merged_patch_obj.name, "sura")
assert_eq(merged_patch_obj.meta.score, 2)
assert(not json.has_path(merged_patch_obj, "meta.old"))
assert(merged_patch_obj.added)
assert(base_patch_obj.meta.old)
assert_eq(json_merge_patch({arr: [1]}, {arr: [2, 3]}).arr.len(), 2)
deleted_path_obj is json.delete_path(merged_patch_obj, "meta.score")
assert(not json.has_path(deleted_path_obj, "meta.score"))
assert(json.has_path(merged_patch_obj, "meta.score"))
deleted_arr_obj is json_delete_path({items: [{id: 1}, {id: 2}]}, "items[0]")
assert_eq(deleted_arr_obj.items[0].id, 2)
set_path_obj is json.set_path(base_patch_obj, "meta.score", 9)
assert_eq(set_path_obj.meta.score, 9)
assert_eq(base_patch_obj.meta.score, 1)
created_path_obj is json_set_path({}, "tool.args[0].url", "file://knowledge")
assert_eq(created_path_obj.tool.args[0].url, "file://knowledge")
root_set_obj is json_set_path({old: true}, "$", {fresh: true})
assert(root_set_obj.fresh)
assert(json.stringify(obj).contains("\"ok\":true"))
assert_eq(json.try_parse("not json", {ok: false}).ok, false)
assert_eq(json_try_parse("not json", 42), 42)

meta is {name: "sura", kind: "lang", score: 9}
assert_eq(dict.keys(meta).join(","), "kind,name,score")
assert_eq(dict.values(meta).join(","), "lang,sura,9")
dict_items_out is dict.items(meta)
assert_eq(dict_items_out[0].key, "kind")
assert_eq(dict_items_out[0].value, "lang")
merged_meta is dict.merge({name: "old", keep: true}, {name: "sura", score: 9})
assert_eq(merged_meta.name, "sura")
assert_eq(merged_meta.keep, true)
picked_meta is dict.pick(merged_meta, ["name", "score"])
assert_eq(picked_meta.score, 9)
missing_pick is dict.pick(merged_meta, ["missing"])
assert_eq(type(missing_pick.missing), "nil")
omitted_meta is dict.omit(merged_meta, ["keep"])
assert_eq(omitted_meta.keep, nil)
assert_eq(dict_get_path({a: {b: 3}}, "a.b"), 3)
assert_eq(dict.get_path({a: {b: 4}}, "a.b"), 4)

agent_schema is {type: "dict", properties: {goal: {type: "string", min_len: 1}, max_steps: {type: "integer", min: 1, max: 5}}, additional: false}
open_schema is json.schema_to_json_schema(agent_schema)
assert_eq(open_schema.type, "object")
assert_eq(open_schema.properties.goal.type, "string")
assert_eq(open_schema.properties.goal.minLength, 1)
assert_eq(open_schema.properties.max_steps.minimum, 1)
assert_eq(open_schema.properties.max_steps.maximum, 5)
assert_eq(open_schema.additionalProperties, false)
pretty_schema is json.pretty(open_schema, 2)
assert_contains(pretty_schema, "\n  ")
assert_eq(json.parse(pretty_schema).type, "object")

fs.write("note.txt", "hello")
assert(fs.exists("note.txt"))
assert_eq(fs.read("note.txt"), "hello")
assert_eq(fs.basename("nested/file.sura"), "file.sura")
assert_eq(file_sha256("note.txt"), sha256("hello"))
assert_eq(sha256_file("note.txt"), sha256("hello"))
assert_eq(fs.sha256("note.txt"), sha256("hello"))
assert_eq(crypto.file_sha256("note.txt"), sha256("hello"))
assert_eq(file_hmac_sha256("secret", "note.txt"), hmac_sha256("secret", "hello"))
assert_eq(hmac_sha256_file("secret", "note.txt"), hmac_sha256("secret", "hello"))
assert_eq(crypto.file_hmac_sha256("secret", "note.txt"), hmac_sha256("secret", "hello"))
assert_eq(fs.write_bytes("blob.bin", [0, 1, 255]), 3)
assert_eq(fs.read_bytes("blob.bin").join(","), "0,1,255")
assert_eq(file_read_bytes("blob.bin")[2], 255)
mkdir("scripts")
fs.write("scripts/a.sura", "print 1")
fs.write("scripts/readme.txt", "notes")
assert_contains(file_glob("*.txt"), "note.txt")
assert_contains(fs.glob("scripts/*.sura"), "scripts/a.sura")
assert_contains(fs.glob("scripts/**/*.sura"), "scripts/a.sura")
fs_tree_dir is "tree_tmp"
mkdir(fs.join(fs_tree_dir, "nested"))
fs.write(fs.join(fs_tree_dir, "nested", "item.txt"), "x")
assert(fs.remove_tree(fs_tree_dir) >= 3)
assert(not fs.exists(fs_tree_dir))
assert_eq(file_remove_tree(fs_tree_dir), 0)
assert(fs.write_json("config.json", {name: "sura", enabled: true}) > 0)
assert_eq(fs.read_json("config.json").name, "sura")
assert_eq(file_read_json("config.json").enabled, true)

db.set("kv.json", "name", "sura")
assert_eq(db.get("kv.json", "name"), "sura")
db.insert("rows.json", {id: 1, kind: "agent", score: 9})
db.insert("rows.json", {id: 2, kind: "agent", score: 12})
db.insert("rows.json", {id: 3, kind: "skip", score: 3})
assert_eq(db.count("rows.json", {kind: "agent"}), 2)
assert_eq(db.query("rows.json", {kind: "agent"}, {sort: "score", desc: true, limit: 1})[0].id, 2)
assert_eq(db_query("rows.json", {}, {sort_by: "id", offset: 1, limit: 1})[0].id, 2)

query is http.query_parse("?q=sura+agent")
assert_eq(query.q, "sura agent")
form_body is http.form_build({q: "sura agent", tag: ["ai", "tools"]})
assert_eq(form_body, "q=sura+agent&tag=ai&tag=tools")
form_data is http.form_parse(form_body + "&tag=extra")
assert_eq(form_data.q, "sura agent")
assert_eq(form_data.tag[2], "extra")
cookies is http.cookie_parse("Cookie: session=abc%20123; theme=dark; repeated=one; repeated=two")
assert_eq(cookies.session, "abc 123")
assert_eq(cookies.repeated[1], "two")
cookie_header is http.cookie_build({session: "abc 123", theme: "dark"})
assert_eq(cookie_header, "session=abc%20123; theme=dark")
assert_eq(http.cookie_get({Cookie: cookie_header}, "theme"), "dark")
assert_eq(http.cookie_get(cookies, "missing", "fallback"), "fallback")
parsed_url is http.url_parse("https://api.example.com:8443/v1/search?q=sura+agent&tag=ai&tag=tools#top")
assert_eq(parsed_url.scheme, "https")
assert_eq(parsed_url.host, "api.example.com")
assert_eq(parsed_url.port, 8443)
assert_eq(parsed_url.path, "/v1/search")
assert_eq(parsed_url.params.q, "sura agent")
assert_eq(parsed_url.params.tag[1], "tools")
assert_eq(url_build(parsed_url), "https://api.example.com:8443/v1/search?q=sura+agent&tag=ai&tag=tools#top")
assert_eq(http.url_build({scheme: "https", host: "api.example.com", path: "v1/search", params: {q: "sura agent"}, fragment: "top"}), "https://api.example.com/v1/search?q=sura%20agent#top")
assert(http.status_ok(204))
assert(not http.status_ok(404))
assert_eq(http.status_text(429), "Too Many Requests")
assert(http.status_retryable(503))
assert(not http_status_retryable(404))
assert_eq(http.retry_after({"Retry-After": "2"}, 100), 2000)
assert_eq(http.retry_after({}, 150), 150)
assert_eq(http.backoff_delays(4, 100, 2, 500).join(","), "100,200,400,500")
assert_eq(http_backoff_delays(3, 50, 3, 500).join(","), "50,150,450")
headers is http.headers_merge(http.auth_bearer("token123"), {"X-Agent": "sura"})
assert_eq(headers.Authorization, "Bearer token123")
assert_eq(headers["X-Agent"], "sura")
assert_eq(http.headers_get(headers, "authorization"), "Bearer token123")
assert(http.headers_has(headers, "x-agent"))
assert_eq(headers_get(headers, "missing", "fallback"), "fallback")
secret_headers is http.headers_redact({Authorization: "Bearer x", "X-Agent": "sura", "X-Api-Key": "secret"}, ["X-Agent"], "***")
assert_eq(secret_headers.Authorization, "***")
assert_eq(secret_headers["X-Agent"], "***")
assert_eq(secret_headers["X-Api-Key"], "***")
content_headers is {"Content-Type": "Application/Problem+JSON; charset=UTF-8"}
assert_eq(http.content_type(content_headers), "application/problem+json")
assert_eq(http.charset(content_headers), "utf-8")
assert(http.is_json(content_headers))
assert(not http_is_json("text/plain; charset=utf-8"))
basic_headers is http.auth_basic("user", "pass")
assert_eq(basic_headers.Authorization, "Basic dXNlcjpwYXNz")
assert(async.cleanup() >= 0)
async_limits is async.limits()
assert(async_limits.max_workers >= 1)
assert(async_limits.max_queue >= 1)
module_scope is async.scope()
module_timer is async.sleep(1, module_scope)
module_join is async.scope_join(module_scope, 1000)
assert(module_join.closed)
assert_eq(module_join.succeeded, 1)
assert(not async.status(module_timer).known)

sse_payload is json.stringify({delta: "Hi"})
sse_text is "event: message\n" + "data: " + sse_payload + "\n\n" + "data: [DONE]\n\n"
assert_eq(json.sse_parse(sse_text)[0].event, "message")
assert_eq(json.sse_data(sse_text, true)[0].delta, "Hi")
ini_text is "name = Sura\nmode: fast\n[agent]\nmodel = llama\nnote = \"hello world\"\n"
ini_cfg is json.ini_parse(ini_text)
assert_eq(ini_cfg.name, "Sura")
assert_eq(ini_cfg.mode, "fast")
assert_eq(ini_cfg.agent.model, "llama")
assert_eq(ini_cfg.agent.note, "hello world")
ini_roundtrip is ini_parse(json.ini_stringify({name: "Sura", agent: {model: "llama", note: "hello world"}}))
assert_eq(ini_roundtrip.agent.note, "hello world")

log.set_file("agent.jsonl", false)
log.set_json(true)
log.event("info", "module smoke", {ok: true})
assert_eq(log.set_level("WARN"), "WARN")
log.info("hidden module info")
log.error("visible module error")
assert_eq(log.get_level(), "WARN")
assert_eq(log.level("DEBUG"), "DEBUG")
log.set_file("", true)
assert(fs.exists("agent.jsonl"))
assert(not fs.read("agent.jsonl").contains("hidden module info"))
assert(fs.read("agent.jsonl").contains("visible module error"))
console.log("module console", "ok", 1)
console.info("module console info")
console.debug("module console debug")
console.warn("module console warn")
console.error("module console error")
console.exception("module console exception")
console.print("module console print")
console.write("module console write")
console.write_line(" line")
console.println("module console println")
console.line("module console line")
console.assert(true, "hidden module console assert")
console.assert(false, "module console assert", 9)
console.time("module timer")
os.wait(1)
module_mid_elapsed_ms is console.time_log("module timer", "checkpoint")
module_elapsed_ms is console.time_end("module timer")
module_stamp_ms is console.time_stamp("module mark")
assert_eq(type(module_elapsed_ms), "number")
assert_eq(type(module_mid_elapsed_ms), "number")
assert_eq(type(module_stamp_ms), "number")
module_count_one is console.count("module-count")
module_count_two is console.count("module-count")
console.count_reset("module-count")
module_count_reset is console.count("module-count")
assert_eq(module_count_one, 1)
assert_eq(module_count_two, 2)
assert_eq(module_count_reset, 1)
console.table([{name: "sura", score: 10}, {name: "module", score: 20}])
console.dir({module: "console", ok: true})
console.dirxml("module dirxml")
console.group("module group")
console.log("inside group")
console.groupEnd()
console.trace("module trace")
console.profile("module profile")
os.wait(1)
module_profile_elapsed is console.profile_end("module profile")
assert_eq(type(module_profile_elapsed), "number")

checks is [check("module check", true), check_eq("module eq", "sura", "sura")]
summary is test.summary(checks)
test.eq(summary.failed, 0)
test.not_contains("sura", "python")
test.type({ok: true}, "dict")
test.len(["plan", "run", "ship"], 3)
test.between(42, 0, 100)
test.approx(0.1 + 0.2, 0.3, 0.000001)

assert_eq(vector.dot([1, 2, 3], [4, 5, 6]), 32)
assert_eq(vector.normalize([3, 4])[0], 0.6)
vec3_module is vector.vec3(1, 2, 3)
assert_eq(vector.dot3(vec3_module, [4, 6, 8]), 40)
assert_eq(vector.cross([1, 0, 0], [0, 1, 0]).join(","), "0,0,1")
assert_eq(vector.distance3([1, 2, 3], [4, 6, 3]), 5)
assert_eq(vector.neg3(vec3_module).join(","), "-1,-2,-3")
module_lerp3 is vector.lerp3([0, 0, 0], [10, 20, 30], 0.25)
assert_approx(module_lerp3[0], 2.5, 0.000001)
assert_approx(module_lerp3[2], 7.5, 0.000001)
assert_eq(vector.project3([3, 4, 0], [1, 0, 0]).join(","), "3,0,0")
assert_eq(vector.reject3([3, 4, 0], [1, 0, 0]).join(","), "0,4,0")
assert_eq(vector.reflect3([1, -2, 0], [0, 1, 0]).join(","), "1,2,0")
assert_approx(vector.angle3([1, 0, 0], [0, 1, 0]), 1.5707963267948966, 0.000001)
assert_eq(vector.transform4([1, 2, 3], [1, 0, 0, 10, 0, 1, 0, 20, 0, 0, 1, 30, 0, 0, 0, 1]).join(","), "11,22,33")
identity3d is graphics3d.identity()
assert_eq(vec3_transform4([1, 2, 3], identity3d).join(","), "1,2,3")
cube3d is graphics3d.cube(2)
assert_eq(cube3d.vertices.len(), 8)
assert_eq(cube3d.faces.len(), 12)
bounds3d is graphics3d.bounds(cube3d)
assert_eq(bounds3d.min.join(","), "-1,-1,-1")
assert_eq(bounds3d.max.join(","), "1,1,1")
moved3d is graphics3d.transform(cube3d, graphics3d.translate(10, 0, 0))
assert_eq(mesh_bounds(moved3d).center.join(","), "10,0,0")
combined3d is graphics3d.mul(graphics3d.translate(1, 2, 3), graphics3d.scale(2, 2, 2))
assert_eq(vec3_transform4([1, 1, 1], combined3d).join(","), "3,4,5")
normals3d is graphics3d.face_normals(cube3d)
assert_eq(normals3d.len(), 12)
assert_approx(vec3_norm(normals3d[0]), 1, 0.000001)
screen3d is graphics3d.project([0, 0, 0], {position: [0, 0, -5], target: [0, 0, 0], fov_deg: 90}, 800, 600)
assert(screen3d.visible)
assert_approx(screen3d.x, 400, 0.000001)
assert_approx(screen3d.y, 300, 0.000001)
docs is [{id: "game", title: "Games", text: "Sura is fast for games.", embedding: [1, 0]}, {id: "agent", title: "Agents", text: "Sura helps AI agents.", embedding: [0.8, 0.2]}]
hits is vector.search([1, 0], docs, 1)
assert_eq(hits[0].item.id, "game")
prepared is rag.prepare("What is Sura good for?", [1, 0], docs, 2)
assert(prepared.context.contains("Sura is fast"))
assert_eq(rag.messages("Question?", "Context")[0].role, "system")

matrix is tensor.matmul([[1, 2], [3, 4]], [[5, 6], [7, 8]])
assert_eq(matrix[0][0], 19)
assert_eq(tensor.shape(matrix)[0], 2)
assert_eq(tensor.flatten(matrix).len(), 4)
assert_eq(tensor.flatten(tensor.clip([[-2, 0], [3, 7]], -1, 4)).join(","), "-1,0,3,4")
assert_eq(tensor.shape(tensor.clip([[1, 2], [3, 4]], 2, 3)).join(","), "2,2")
assert_eq(tensor.sum([[1, 2], [3, 4]]), 10)
assert_eq(tensor.mean([[1, 2], [3, 4]]), 2.5)
assert_approx(tensor.variance([[1, 2], [3, 4]]), 1.25, 0.000001)
assert_approx(tensor.std([[1, 2], [3, 4]]), 1.11803398875, 0.000001)
assert_eq(tensor.min([[1, -2], [3, 4]]), -2)
assert_eq(tensor.max([[1, -2], [3, 4]]), 4)
assert_eq(tensor.argmin([[1, -2], [-2, 4]]), 1)
assert_eq(tensor.argmax([[1, 4], [4, -2]]), 1)
zscore_vals is tensor.zscore([1, 2, 3])
assert_approx(tensor.mean(zscore_vals), 0, 0.000001)
assert_approx(tensor.std(zscore_vals), 1, 0.000001)
assert_approx(zscore_vals[1], 0, 0.000001)
assert_eq(tensor.flatten(tensor.zscore([[5, 5], [5, 5]])).join(","), "0,0,0,0")
assert_eq(tensor.shape(tensor.zscore([[1, 2], [3, 4]])).join(","), "2,2")
softmax_probs is tensor.softmax([1, 2, 3])
assert_approx(tensor.sum(softmax_probs), 1, 0.000001)
assert_eq(tensor.argmax(softmax_probs), 2)
assert_between(softmax_probs[2], 0.66, 0.67)
assert_eq(tensor.shape(tensor.softmax([[1, 2], [3, 4]])).join(","), "2,2")
assert_eq(type(tensor.mean([])), "nil")
assert_eq(type(tensor.variance([])), "nil")
assert_eq(type(tensor.std([])), "nil")
assert_eq(type(tensor.min([])), "nil")
assert_eq(type(tensor.max([])), "nil")
assert_eq(type(tensor.argmin([])), "nil")
assert_eq(type(tensor.argmax([])), "nil")
assert_eq(tensor.clip([], -1, 1).len(), 0)
assert_eq(tensor.zscore([]).len(), 0)
assert_eq(tensor.softmax([]).len(), 0)

nn_smoke_model is nn.mlp([2, 3, 1], {activation: "tanh", task: "binary", seed: 5})
assert_eq(nn.summary(nn_smoke_model).architecture.join(","), "2,3,1")
assert_eq(ai.summary(nn_smoke_model).parameters, 13)
assert_eq(nn_summary(nn_smoke_model).parameters, 13)
assert_eq(nn.predict(nn_smoke_model, [0, 1]).len(), 1)
assert_eq(nn.one_hot([0, 2], 3)[1].join(","), "0,0,1")
nn_smoke_scaler is nn.fit_standardizer([[1, 5], [3, 5]])
assert_eq(nn.standardize([2, 5], nn_smoke_scaler).join(","), "0,0")
assert_eq(nn.split([[0], [1]], [0, 1], {test_count: 1, shuffle: false}).test.targets[0], 1)

autograd_smoke_parameter is autograd.parameter([1, 2])
assert_eq(autograd.requires_grad(autograd_smoke_parameter), true)
assert_eq(autograd.shape(autograd_smoke_parameter).join(","), "2")
autograd_smoke_loss is autograd.sum(autograd.mul(autograd_smoke_parameter, autograd_smoke_parameter))
autograd.backward(autograd_smoke_loss)
assert_eq(autograd.grad(autograd_smoke_parameter).join(","), "2,4")
autograd.zero_grad([autograd_smoke_parameter])
assert_eq(autograd_grad(autograd_smoke_parameter).join(","), "0,0")

events is stream.from([{kind: "log", msg: "start"}, {kind: "metric", msg: "cpu"}, {kind: "log", msg: "stop"}])
assert_eq(stream.join(stream.map(stream.filter(events, {kind: "log"}), "msg"), " | "), "start | stop")
assert_eq(stream.batch(stream.from(["a", "b", "c"]), 2)[0].len(), 2)
metric_stream is stream.from([{ms: 10}, {ms: 20}, {ms: 30}])
assert_eq(stream.sum(metric_stream, "ms"), 60)
assert_eq(stream.count(metric_stream), 0)
assert_eq(stream_avg(stream_from([2, 4, 6])), 4)
assert_eq(type(stream.avg(stream.from([]))), "nil")

random.seed(2026)
roll is random.int(1, 6)
random.seed(2026)
test.eq(random.int(1, 6), roll)
assert(random.float(10, 20) >= 10)
pick is random.choice([10, 20, 30])
assert(pick == 10 or pick == 20 or pick == 30)
shuffled is random.shuffle([1, 2, 3, 4])
assert_eq(shuffled.len(), 4)
assert_eq(random.bytes(4).len(), 4)
assert_eq(type(random.bool(1.0)), "bool")

assert_eq(type(python.available()), "bool")
assert_eq(type(python.executable()), "string")
assert_eq(ffi.name, "ffi")
assert_eq(plugin.name, "plugin")

spec is tool.spec("http_get", {url: "file://" + fs.abs("note.txt")})
assert(tool.validate(spec))
assert_contains(tool.schema("http_get").required, "url")

messages is llm.messages("You are concise", "Summarize Sura")
assert_eq(messages[0].role, "system")
assert(llm.request_json("model", messages, 0.2).contains("\"model\":\"model\""))
structured is llm.request_schema("model", messages, agent_schema, 0.2, "agent_plan")
assert_eq(structured.response_format.type, "json_schema")
assert_eq(structured.response_format.json_schema.name, "agent_plan")
assert_eq(structured.response_format.json_schema.schema.properties.goal.type, "string")
assert(structured.response_format.json_schema.strict)
structured_json is llm.request_schema_json("model", messages, agent_schema, 0.2, "agent_plan")
assert(contains(structured_json, "\"response_format\""))
assert(contains(structured_json, "\"json_schema\""))
tool_defs is llm.tools(["http_get", "http_request"])
assert_eq(tool_defs[0].type, "function")
assert_eq(tool_defs[0].function.name, "http_get")
assert_contains(tool_defs[0].function.parameters.required, "url")
assert_eq(tool_defs[0].function.parameters.properties.url.type, "string")
assert_eq(tool_defs[1].function.name, "http_request")
assert_eq(tool_defs[1].function.parameters.properties.form.type, "object")
tool_request is llm.request_tools("model", messages, ["http_get"], 0)
assert_eq(tool_request.tools[0].function.name, "http_get")
tool_request_json is llm.request_tools_json("model", messages, ["http_get"], 0)
assert(contains(tool_request_json, "\"tools\""))
assert(contains(tool_request_json, "\"http_get\""))
tool_schema_request is llm.request_tools_schema("model", messages, ["http_get"], agent_schema, 0, "agent_plan")
assert_eq(tool_schema_request.tools[0].function.name, "http_get")
assert_eq(tool_schema_request.response_format.json_schema.name, "agent_plan")
assert_eq(tool_schema_request.response_format.json_schema.schema.properties.goal.type, "string")
tool_schema_request_json is llm.request_tools_schema_json("model", messages, ["http_get"], agent_schema, 0, "agent_plan")
assert(contains(tool_schema_request_json, "\"tools\""))
assert(contains(tool_schema_request_json, "\"response_format\""))
llm_mock_path is "llm_mock_response.json"
fs.write(llm_mock_path, json.stringify({choices: [{message: {content: "mock ok"}}]}))
llm_mock_url is "file://" + fs.abs(llm_mock_path).replace("\\", "/")
assert_eq(llm.extract_text(llm.chat(llm_mock_url, "test-key", "model", messages, 0.2)), "mock ok")
assert_eq(llm.extract_text(llm.chat_request(llm_mock_url, "test-key", tool_schema_request)), "mock ok")
assert_eq(llm.extract_text(llm.chat_request(llm_mock_url, "test-key", tool_schema_request_json)), "mock ok")
fs.delete(llm_mock_path)
assert_eq(llm.extract_text({choices: [{message: {content: "ok"}}]}), "ok")
json_response is {choices: [{message: {content: json.stringify({goal: "ship", max_steps: 3})}}]}
json_output is llm.extract_json(json_response, agent_schema)
assert_eq(json_output.goal, "ship")
assert_eq(json_output.max_steps, 3)
tool_note_path is "llm_tool_note.txt"
fs.write(tool_note_path, "tool context")
tool_note_url is "file://" + fs.abs(tool_note_path).replace("\\", "/")
model_tool_response is {choices: [{message: {tool_calls: [{id: "call_1", function: {name: "http_get", arguments: json.stringify({url: tool_note_url})}}]}}]}
next_messages is llm.next_messages(messages, model_tool_response, {tools: ["http_get"], url_prefixes: ["file://"]})
assert_eq(next_messages[length(messages)].role, "assistant")
assert_eq(next_messages[length(messages) + 1].role, "tool")
assert_eq(next_messages[length(messages) + 1].tool_call_id, "call_1")
assert(contains(next_messages[length(messages) + 1].content, "tool context"))
next_request is llm.next_request("model", messages, model_tool_response, {tools: ["http_get"], url_prefixes: ["file://"]}, ["http_get"], 0)
assert_eq(next_request.messages[length(messages) + 1].role, "tool")
assert_eq(next_request.tools[0].function.name, "http_get")
assert(contains(llm.next_request_json("model", messages, model_tool_response, {tools: ["http_get"], url_prefixes: ["file://"]}, ["http_get"], 0), "\"tools\""))
next_schema_request is llm.next_schema_request("model", messages, model_tool_response, {tools: ["http_get"], url_prefixes: ["file://"]}, ["http_get"], agent_schema, 0, "agent_plan")
assert_eq(next_schema_request.messages[length(messages) + 1].role, "tool")
assert_eq(next_schema_request.response_format.json_schema.name, "agent_plan")
assert(contains(llm.next_schema_request_json("model", messages, model_tool_response, {tools: ["http_get"], url_prefixes: ["file://"]}, ["http_get"], agent_schema, 0, "agent_plan"), "\"response_format\""))
fs.delete(tool_note_path)
usage is llm.usage({usage: {prompt_tokens: 3, completion_tokens: 4, total_tokens: 7}})
assert_eq(usage.prompt_tokens, 3)
assert_eq(usage.output_tokens, 4)
responses_usage is llm_usage({usage: {input_tokens: 5, output_tokens: 6}})
assert_eq(responses_usage.total_tokens, 11)
cost is llm.cost({usage: {input_tokens: 1000000, output_tokens: 500000}}, {input_per_million: 2, output_per_million: 8, currency: "USD"})
assert_eq(cost.input_cost, 2)
assert_eq(cost.output_cost, 4)
assert_eq(cost.total_cost, 6)
assert_eq(cost.currency, "USD")
alias_cost is llm_cost({usage: {prompt_tokens: 1000000, completion_tokens: 1000000}}, {prompt_per_million: 1, completion_per_million: 2})
assert_eq(alias_cost.total_cost, 3)
budget is llm.budget({usage: {input_tokens: 1000000, output_tokens: 500000}}, {input_per_million: 2, output_per_million: 8}, 7)
assert_eq(budget.within_budget, true)
assert_eq(budget.over_budget, false)
assert_eq(budget.remaining, 1)
over_budget is llm_budget({usage: {input_tokens: 1000000, output_tokens: 500000}}, {input_per_million: 2, output_per_million: 8}, 5)
assert_eq(over_budget.within_budget, false)
assert_eq(over_budget.over_budget, true)
assert_eq(over_budget.remaining, -1)
print "stdlib_modules_smoke: PASS"
'@

    $result = Run-Engine -Script $script
    if ($result.Code -ne 0 -or $result.Output -notmatch "stdlib_modules_smoke: PASS") {
        Write-Output $result.Output
        throw "expected stdlib module smoke to pass"
    }

    "stdlib_modules_smoke: PASS"
}
finally {
    if (Test-Path $temp) {
        Remove-Item -LiteralPath $temp -Recurse -Force
    }
}
