<#
.SYNOPSIS
    Collect a shareable bug report: versions, hashes, target, and an optional
    minimal reproduction.

.DESCRIPTION
    A Sura bug report is only actionable if the reader can tell which binary
    produced it. "Sura 1.11.1 crashes" is not enough - the engine is rebuilt
    often and 1.11.1 has covered many different binaries. This records the
    engine SHA-256 and byte count alongside the version, plus the JIT target
    the engine selected, so a maintainer can reproduce against the same
    artifact instead of guessing.

    What is deliberately NOT collected, because bug reports get pasted into
    public issues:

      * environment variables - the usual home of tokens and keys;
      * any file the user did not explicitly pass as -Repro;
      * absolute paths outside the repository. The user profile directory is
        replaced with ~ wherever it appears.

    The report is deterministic apart from the timestamp: the same tree and
    machine produce identical output, so two reports can be diffed to see what
    actually changed between them.

.PARAMETER Engine
    Engine executable to describe. Defaults to .\SuraLanguage.exe.

.PARAMETER Repro
    Optional .sura file reproducing the problem. It is embedded verbatim, so
    pass a minimal case rather than a private program.

.PARAMETER Out
    Output path. Defaults to bug_report.md in the current directory.

.EXAMPLE
    .\tools\sura_bug_report.ps1

.EXAMPLE
    .\tools\sura_bug_report.ps1 -Repro .\crash.sura -Out issue-42.md
#>
param(
    [string]$Engine = "",
    [string]$Repro = "",
    [string]$Out = "bug_report.md"
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path | Split-Path -Parent
if (-not $Engine) { $Engine = Join-Path $root "SuraLanguage.exe" }

# Everything user-identifying that might appear in a path gets folded to ~.
$homeDir = [System.Environment]::GetFolderPath("UserProfile")
function Redact {
    param([string]$Text)
    if ([string]::IsNullOrEmpty($Text)) { return $Text }
    if ($homeDir) { $Text = $Text.Replace($homeDir, "~") }
    return $Text
}

function Run-Capture {
    param([string]$File, [string[]]$ExeArgs, [int]$Timeout = 30)
    if (-not (Test-Path -LiteralPath $File)) { return "" }
    $o = [System.IO.Path]::GetTempFileName()
    $e = [System.IO.Path]::GetTempFileName()
    try {
        $p = Start-Process -FilePath $File -ArgumentList $ExeArgs -NoNewWindow -PassThru `
                           -RedirectStandardOutput $o -RedirectStandardError $e
        $null = $p.Handle
        if (-not $p.WaitForExit($Timeout * 1000)) { try { $p.Kill() } catch {}; return "" }
        $p.WaitForExit()
        # stderr matters more than stdout here: runtime errors, the usual
        # subject of a bug report, are written there. Capturing only stdout
        # produced reports whose reproduction section read "(no output)" for a
        # program that had in fact raised.
        $stdout = ([System.IO.File]::ReadAllText($o)).Trim()
        $stderr = ([System.IO.File]::ReadAllText($e)).Trim()
        if ($stderr -and $stdout) { return $stdout + "`n" + $stderr }
        if ($stderr) { return $stderr }
        return $stdout
    } catch { return "" }
    finally {
        foreach ($f in @($o, $e)) { if (Test-Path -LiteralPath $f) { Remove-Item -LiteralPath $f -Force -ErrorAction SilentlyContinue } }
    }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Sura bug report")
$lines.Add("")
$lines.Add("Generated by ``tools/sura_bug_report.ps1``. Environment variables and")
$lines.Add("files other than the reproduction below are deliberately not included.")
$lines.Add("")
$lines.Add("- Generated UTC: " + [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ"))
$lines.Add("")

# ── Engine identity ────────────────────────────────────────────────────────
$lines.Add("## Engine")
$lines.Add("")
$lines.Add("| Field | Value |")
$lines.Add("| --- | --- |")
if (Test-Path -LiteralPath $Engine) {
    $item = Get-Item -LiteralPath $Engine
    $hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $Engine).Hash.ToLower()
    $ver = Run-Capture $Engine @("--version")
    $verText = if ($ver) { $ver } else { "unavailable" }
    $lines.Add("| Version | $verText |")
    $lines.Add("| SHA-256 | ``$hash`` |")
    $lines.Add("| Bytes | $($item.Length) |")
    $lines.Add("| Path | ``$(Redact $item.FullName)`` |")
} else {
    $lines.Add("| Version | **engine not found at $(Redact $Engine)** |")
}
$lines.Add("")

# ── JIT target, straight from the engine's own machine-readable report ──────
$jitInfo = Run-Capture $Engine @("--jit-info-json")
$lines.Add("## JIT target")
$lines.Add("")
if ($jitInfo) {
    $lines.Add('```json')
    $lines.Add($jitInfo)
    $lines.Add('```')
} else {
    $lines.Add("`--jit-info-json` produced no output.")
}
$lines.Add("")

# ── Host ───────────────────────────────────────────────────────────────────
$lines.Add("## Host")
$lines.Add("")
$lines.Add("| Field | Value |")
$lines.Add("| --- | --- |")
$lines.Add("| OS | $([System.Environment]::OSVersion.VersionString) |")
$lines.Add("| 64-bit OS | $([System.Environment]::Is64BitOperatingSystem) |")
$lines.Add("| Logical CPUs | $([System.Environment]::ProcessorCount) |")
$lines.Add("| PowerShell | $($PSVersionTable.PSVersion) |")

$cxx = $env:SURA_CXX
if (-not $cxx) { $cxx = "C:\msys64\mingw64\bin\g++.exe" }
$cxxVer = ""
if (Test-Path -LiteralPath $cxx) {
    $cxxVer = (Run-Capture $cxx @("--version")) -split "`n" | Select-Object -First 1
}
$cxxText = if ($cxxVer) { Redact $cxxVer } else { "not found at $(Redact $cxx)" }
$lines.Add("| C++ compiler | $cxxText |")

# GPU only matters because the CUDA tests are part of the suite.
$gpu = ""
try { $gpu = (& nvidia-smi --query-gpu=name,driver_version --format=csv,noheader 2>$null | Select-Object -First 1) } catch { $gpu = "" }
$gpuText = if ($gpu) { $gpu } else { "none detected" }
$lines.Add("| GPU | $gpuText |")
$lines.Add("")

# ── Reproduction ───────────────────────────────────────────────────────────
$lines.Add("## Reproduction")
$lines.Add("")
if ($Repro) {
    if (-not (Test-Path -LiteralPath $Repro)) {
        Write-Error "Reproduction file not found: $Repro"
        exit 2
    }
    $reproText = Get-Content -LiteralPath $Repro -Raw
    $lines.Add("Source (``$(Split-Path $Repro -Leaf)``):")
    $lines.Add("")
    $lines.Add('```')
    $lines.Add($reproText.TrimEnd())
    $lines.Add('```')
    $lines.Add("")

    foreach ($mode in @(@{ n = "register VM"; a = @() }, @{ n = "--jit"; a = @("--jit") })) {
        $runArgs = @() + $mode.a + @((Resolve-Path -LiteralPath $Repro).Path)
        $output = Run-Capture $Engine $runArgs 60
        $lines.Add("Output ($($mode.n)):")
        $lines.Add("")
        $lines.Add('```')
        $outText = if ($output) { Redact $output } else { "(no output)" }
        $lines.Add($outText)
        $lines.Add('```')
        $lines.Add("")
    }
    $lines.Add("Both modes are shown because a difference between them is itself the")
    $lines.Add("finding - it means the native JIT and the interpreter disagree.")
} else {
    $lines.Add("No reproduction attached. Re-run with ``-Repro <file.sura>`` and a")
    $lines.Add("minimal case; the engine is run under both the register VM and")
    $lines.Add("``--jit`` so a codegen difference shows up on its own.")
}
$lines.Add("")

$lines.Add("## Not included")
$lines.Add("")
$lines.Add("Environment variables, credentials, and any file not passed as")
$lines.Add("``-Repro``. Paths under the user profile are shown as ``~``. Check the")
$lines.Add("reproduction above before posting - it is embedded verbatim.")

Set-Content -LiteralPath $Out -Value ($lines -join "`n") -Encoding UTF8
Write-Host ("Wrote {0}" -f $Out)
if (Test-Path -LiteralPath $Engine) {
    Write-Host ("  engine : {0}" -f (Run-Capture $Engine @("--version")))
    Write-Host ("  sha256 : {0}" -f (Get-FileHash -Algorithm SHA256 -LiteralPath $Engine).Hash.ToLower())
}
$reproText2 = if ($Repro) { $Repro } else { "none" }
Write-Host ("  repro  : {0}" -f $reproText2)
exit 0
