param(
    [string]$Surapkg = ".\surapkg.exe"
)

$ErrorActionPreference = "Stop"

$temp = Join-Path ([System.IO.Path]::GetTempPath()) ("sura_registry_client_" + [System.Guid]::NewGuid().ToString("N"))
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-Text {
    param([string]$Path, [string]$Text)
    $parent = Split-Path -Parent $Path
    if ($parent) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
    [System.IO.File]::WriteAllText($Path, $Text, $utf8NoBom)
}

function Run-Pkg {
    param([string[]]$PkgArgs)
    $old = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    $out = & $Surapkg @PkgArgs 2>&1 | ForEach-Object { "$_" }
    $code = $LASTEXITCODE
    $ErrorActionPreference = $old
    return @{ Code = $code; Output = ($out -join "`n") }
}

$oldRegistry = $env:SURA_REGISTRY
$oldRegistryUrl = $env:SURA_REGISTRY_URL
try {
    New-Item -ItemType Directory -Force -Path $temp | Out-Null
    $registry = Join-Path $temp "registry"
    $pkg = Join-Path $temp "math_extra"
    $env:SURA_REGISTRY = $registry
    $env:SURA_REGISTRY_URL = $null

    Write-Text (Join-Path $pkg "sura.pkg.json") @"
{
  "name": "math_extra",
  "version": "0.1.0",
  "main": "src/math_extra.sura",
  "dependencies": {}
}
"@
    Write-Text (Join-Path $pkg "src/math_extra.sura") @"
func double(x) do
  return x * 2
end
"@

    $dryRunReportPath = Join-Path $temp "publish-dry-run-report.json"
    $dryRun = Run-Pkg -PkgArgs @("publish", $pkg, "--dry-run", "--json", $dryRunReportPath)
    if ($dryRun.Code -ne 0 -or $dryRun.Output -notmatch "dry-run publish passed") {
        Write-Output $dryRun.Output
        throw "expected publish --dry-run to pass"
    }
    if (Test-Path (Join-Path $registry "math_extra")) {
        Write-Output $dryRun.Output
        throw "expected publish --dry-run not to write registry package"
    }
    if (-not (Test-Path $dryRunReportPath)) {
        Write-Output $dryRun.Output
        throw "expected publish --dry-run --json to write a report"
    }
    $dryRunReport = [System.IO.File]::ReadAllText($dryRunReportPath, [System.Text.Encoding]::UTF8) | ConvertFrom-Json
    if ($dryRunReport.schema -ne "sura.package.publish.v1" -or
        $dryRunReport.package -ne "math_extra" -or
        $dryRunReport.version -ne "0.1.0" -or
        $dryRunReport.passed -ne $true -or
        $dryRunReport.dry_run -ne $true -or
        $dryRunReport.remote_uploaded -ne $false -or
        [string]::IsNullOrWhiteSpace($dryRunReport.hash) -or
        -not (Test-Path $dryRunReport.bundle)) {
        $dryRunReport | ConvertTo-Json -Depth 6
        throw "unexpected publish --dry-run JSON report"
    }

    $publishReportPath = Join-Path $temp "publish-report.json"
    $publish = Run-Pkg -PkgArgs @("publish", $pkg, "--json", $publishReportPath)
    if ($publish.Code -ne 0 -or $publish.Output -notmatch "published") {
        Write-Output $publish.Output
        throw "expected local publish to pass"
    }
    if (-not (Test-Path $publishReportPath)) {
        Write-Output $publish.Output
        throw "expected publish --json to write a report"
    }
    $publishReport = [System.IO.File]::ReadAllText($publishReportPath, [System.Text.Encoding]::UTF8) | ConvertFrom-Json
    if ($publishReport.schema -ne "sura.package.publish.v1" -or
        $publishReport.package -ne "math_extra" -or
        $publishReport.version -ne "0.1.0" -or
        $publishReport.passed -ne $true -or
        $publishReport.dry_run -ne $false -or
        $publishReport.remote_uploaded -ne $false -or
        [string]::IsNullOrWhiteSpace($publishReport.hash) -or
        -not (Test-Path $publishReport.bundle)) {
        $publishReport | ConvertTo-Json -Depth 6
        throw "unexpected publish JSON report"
    }

    $advisory = Run-Pkg -PkgArgs @(
        "advisory", "math_extra@0.1.0",
        "--severity", "high",
        "--title", "Unsafe smoke API",
        "--description", "Smoke advisory generated by local CLI",
        "--url", "https://example.com/sura-advisory",
        "--json"
    )
    if ($advisory.Code -ne 0) {
        Write-Output $advisory.Output
        throw "expected local registry advisory --json to pass"
    }
    $advisoryReport = $advisory.Output | ConvertFrom-Json
    if ($advisoryReport.schema -ne "sura.registry.advisory.v1" -or
        $advisoryReport.source -ne "local" -or
        $advisoryReport.advisory.name -ne "math_extra" -or
        $advisoryReport.advisory.version -ne "0.1.0" -or
        $advisoryReport.advisory.severity -ne "high" -or
        $advisoryReport.advisory.status -ne "active" -or
        $advisoryReport.advisory.title -ne "Unsafe smoke API" -or
        [string]::IsNullOrWhiteSpace($advisoryReport.advisory.id)) {
        Write-Output ($advisoryReport | ConvertTo-Json -Depth 6)
        throw "unexpected local advisory JSON report"
    }
    if (-not (Test-Path (Join-Path $registry "advisories.json"))) {
        throw "expected local advisory command to write advisories.json"
    }
    $advisoriesJson = Run-Pkg -PkgArgs @("advisories", "math_extra@0.1.0", "--severity", "high", "--json")
    if ($advisoriesJson.Code -ne 0) {
        Write-Output $advisoriesJson.Output
        throw "expected local advisories --json to pass"
    }
    $advisoriesReport = $advisoriesJson.Output | ConvertFrom-Json
    $advisoryItems = @($advisoriesReport.advisories)
    $advisoryActions = @($advisoriesReport.next_actions)
    if ($advisoriesReport.schema -ne "sura.registry.advisories.v1" -or
        $advisoriesReport.source -ne "local" -or
        $advisoriesReport.count -ne 1 -or
        $advisoryItems[0].title -ne "Unsafe smoke API" -or
        $advisoryItems[0].severity -ne "high") {
        throw "expected local advisories --json to list created advisory"
    }
    if ($advisoryActions.Count -ne 1 -or
        $advisoryActions[0].advisory_id -ne $advisoryItems[0].id -or
        $advisoryActions[0].target -ne "math_extra@0.1.0" -or
        $advisoryActions[0].severity -ne "high" -or
        $advisoryActions[0].status -ne "active" -or
        $advisoryActions[0].action -notmatch "surapkg update" -or
        $advisoryActions[0].action -notmatch "surapkg audit") {
        $advisoriesReport | ConvertTo-Json -Depth 6
        throw "expected local advisories --json to include high-severity next_actions"
    }
    $advisoriesHighGate = Run-Pkg -PkgArgs @("advisories", "math_extra@0.1.0", "--fail-on", "high", "--json")
    if ($advisoriesHighGate.Code -eq 0) {
        Write-Output $advisoriesHighGate.Output
        throw "expected local advisories --fail-on high to fail on active high advisory"
    }
    $highGateReport = $advisoriesHighGate.Output | ConvertFrom-Json
    if ($highGateReport.passed -ne $false -or
        $highGateReport.fail_on -ne "high" -or
        $highGateReport.failing_count -ne 1 -or
        @($highGateReport.next_actions).Count -ne 1) {
        $highGateReport | ConvertTo-Json -Depth 6
        throw "expected local advisories --fail-on high JSON gate report"
    }
    $advisoriesCriticalGate = Run-Pkg -PkgArgs @("advisories", "math_extra@0.1.0", "--fail-on", "critical", "--json")
    if ($advisoriesCriticalGate.Code -ne 0) {
        Write-Output $advisoriesCriticalGate.Output
        throw "expected local advisories --fail-on critical to pass for high advisory"
    }
    $criticalGateReport = $advisoriesCriticalGate.Output | ConvertFrom-Json
    if ($criticalGateReport.passed -ne $true -or
        $criticalGateReport.fail_on -ne "critical" -or
        $criticalGateReport.failing_count -ne 0) {
        $criticalGateReport | ConvertTo-Json -Depth 6
        throw "expected local advisories --fail-on critical JSON pass report"
    }

    $indexReportPath = Join-Path $temp "index-report.json"
    $index = Run-Pkg -PkgArgs @("index", "--json=$indexReportPath")
    if ($index.Code -ne 0 -or $index.Output -notmatch "wrote") {
        Write-Output $index.Output
        throw "expected registry index --json to pass"
    }
    if (-not (Test-Path $indexReportPath)) {
        Write-Output $index.Output
        throw "expected index --json to write a report"
    }
    $indexReport = [System.IO.File]::ReadAllText($indexReportPath, [System.Text.Encoding]::UTF8) | ConvertFrom-Json
    $indexPackages = @($indexReport.packages)
    if ($indexReport.schema -ne "sura.registry.index.v1" -or
        $indexReport.passed -ne $true -or
        $indexReport.package_count -ne 1 -or
        $indexReport.yanked_count -ne 0 -or
        $indexPackages.Count -ne 1 -or
        $indexPackages[0].name -ne "math_extra" -or
        $indexPackages[0].version -ne "0.1.0" -or
        $indexPackages[0].yanked -ne $false -or
        [string]::IsNullOrWhiteSpace($indexPackages[0].hash) -or
        [string]::IsNullOrWhiteSpace($indexPackages[0].bundle)) {
        Write-Output ($indexReport | ConvertTo-Json -Depth 6)
        throw "unexpected index JSON report"
    }

    Write-Text (Join-Path $registry "stats.json") @"
{
  "downloads": {"math_extra@0.1.0": 3},
  "publishes": {"math_extra@0.1.0": 1},
  "downloadDays": {"2026-01-02": {"math_extra@0.1.0": 3}},
  "publishDays": {"2026-01-01": {"math_extra@0.1.0": 1}},
  "lastPublish": {"name": "math_extra", "version": "0.1.0", "user": "local", "at": "2026-01-01T00:00:00Z"}
}
"@

    $search = Run-Pkg -PkgArgs @("search", "math")
    if ($search.Code -ne 0 -or $search.Output -notmatch "math_extra@0.1.0") {
        Write-Output $search.Output
        throw "expected registry search to find math_extra"
    }
    $searchJson = Run-Pkg -PkgArgs @("search", "math", "--json")
    if ($searchJson.Code -ne 0) {
        Write-Output $searchJson.Output
        throw "expected registry search --json to pass"
    }
    $searchReport = $searchJson.Output | ConvertFrom-Json
    if ($searchReport.schema -ne "sura.registry.search.v1" -or
        $searchReport.query -ne "math" -or
        $searchReport.count -ne 1 -or
        $searchReport.packages[0].name -ne "math_extra" -or
        $searchReport.packages[0].version -ne "0.1.0" -or
        $searchReport.packages[0].yanked -ne $false -or
        [string]::IsNullOrWhiteSpace($searchReport.packages[0].bundle)) {
        throw "expected registry search --json to include math_extra metadata"
    }

    $noMatch = Run-Pkg -PkgArgs @("search", "missing_package")
    if ($noMatch.Code -ne 0 -or $noMatch.Output -notmatch "No registry packages matched") {
        Write-Output $noMatch.Output
        throw "expected registry search miss to be graceful"
    }
    $noMatchJson = Run-Pkg -PkgArgs @("search", "missing_package", "--json")
    if ($noMatchJson.Code -ne 0) {
        Write-Output $noMatchJson.Output
        throw "expected registry search miss --json to pass"
    }
    $noMatchReport = $noMatchJson.Output | ConvertFrom-Json
    if ($noMatchReport.schema -ne "sura.registry.search.v1" -or
        $noMatchReport.query -ne "missing_package" -or
        $noMatchReport.count -ne 0 -or
        ($null -ne $noMatchReport.packages -and @($noMatchReport.packages).Count -ne 0)) {
        throw "expected registry search miss --json to return empty package list"
    }

    $yank = Run-Pkg -PkgArgs @("yank", "math_extra@0.1.0", "bad", "release", "--json")
    if ($yank.Code -ne 0) {
        Write-Output $yank.Output
        throw "expected local registry yank --json to pass"
    }
    $yankReport = $yank.Output | ConvertFrom-Json
    if ($yankReport.schema -ne "sura.registry.yank.v1" -or
        $yankReport.source -ne "local" -or
        $yankReport.name -ne "math_extra" -or
        $yankReport.version -ne "0.1.0" -or
        $yankReport.yanked -ne $true -or
        $yankReport.reason -ne "bad release") {
        throw "expected local yank --json to report yanked package state"
    }
    $yanks = Run-Pkg -PkgArgs @("yanks", "math_extra", "--json")
    if ($yanks.Code -ne 0) {
        Write-Output $yanks.Output
        throw "expected local registry yanks --json to pass"
    }
    $yanksReport = $yanks.Output | ConvertFrom-Json
    $yankItems = @($yanksReport.yanks)
    if ($yanksReport.schema -ne "sura.registry.yanks.v1" -or
        $yanksReport.source -ne "local" -or
        $yanksReport.query -ne "math_extra" -or
        $yanksReport.count -ne 1 -or
        $yankItems[0].name -ne "math_extra" -or
        $yankItems[0].version -ne "0.1.0" -or
        $yankItems[0].reason -ne "bad release") {
        throw "expected local yanks --json to list yanked package state"
    }
    $yankedSearch = Run-Pkg -PkgArgs @("search", "math", "--json")
    if ($yankedSearch.Code -ne 0) {
        Write-Output $yankedSearch.Output
        throw "expected registry search after local yank to pass"
    }
    $yankedSearchReport = $yankedSearch.Output | ConvertFrom-Json
    if ($yankedSearchReport.packages[0].yanked -ne $true) {
        throw "expected search --json to expose local yanked package metadata"
    }
    $unyank = Run-Pkg -PkgArgs @("unyank", "math_extra@0.1.0", "--json")
    if ($unyank.Code -ne 0) {
        Write-Output $unyank.Output
        throw "expected local registry unyank --json to pass"
    }
    $unyankReport = $unyank.Output | ConvertFrom-Json
    if ($unyankReport.schema -ne "sura.registry.yank.v1" -or
        $unyankReport.source -ne "local" -or
        $unyankReport.yanked -ne $false) {
        throw "expected local unyank --json to report restored package state"
    }

    $stats = Run-Pkg -PkgArgs @("stats", "math_extra")
    if ($stats.Code -ne 0 -or $stats.Output -notmatch "Downloads" -or $stats.Output -notmatch "math_extra@0.1.0  3") {
        Write-Output $stats.Output
        throw "expected registry stats to show downloads"
    }
    $statsJson = Run-Pkg -PkgArgs @("stats", "math_extra", "--json")
    if ($statsJson.Code -ne 0) {
        Write-Output $statsJson.Output
        throw "expected registry stats --json to pass"
    }
    $statsReport = $statsJson.Output | ConvertFrom-Json
    $statsDownloads = @($statsReport.downloads)
    $statsPublishes = @($statsReport.publishes)
    if ($statsReport.schema -ne "sura.registry.stats.v1" -or
        $statsReport.query -ne "math_extra" -or
        $statsDownloads.Count -ne 1 -or
        $statsDownloads[0].package -ne "math_extra@0.1.0" -or
        $statsDownloads[0].count -ne 3 -or
        $statsPublishes.Count -ne 1 -or
        $statsPublishes[0].count -ne 1 -or
        $statsReport.last_publish.name -ne "math_extra") {
        throw "expected registry stats --json to include download, publish, and last publish metadata"
    }

    $analytics = Run-Pkg -PkgArgs @("analytics", "math_extra")
    if ($analytics.Code -ne 0 -or
        $analytics.Output -notmatch "Download analytics" -or
        $analytics.Output -notmatch "Top downloads" -or
        $analytics.Output -notmatch "2026-01-02\s+math_extra@0\.1\.0\s+3") {
        Write-Output $analytics.Output
        throw "expected registry analytics to show daily downloads"
    }
    $analyticsJson = Run-Pkg -PkgArgs @("analytics", "math_extra", "--json")
    if ($analyticsJson.Code -ne 0) {
        Write-Output $analyticsJson.Output
        throw "expected registry analytics --json to pass"
    }
    $analyticsReport = $analyticsJson.Output | ConvertFrom-Json
    $topDownloads = @($analyticsReport.top_downloads)
    $dailyDownloads = @($analyticsReport.daily_downloads)
    if ($analyticsReport.schema -ne "sura.registry.analytics.v1" -or
        $analyticsReport.query -ne "math_extra" -or
        $topDownloads.Count -ne 1 -or
        $topDownloads[0].package -ne "math_extra@0.1.0" -or
        $topDownloads[0].count -ne 3 -or
        $dailyDownloads.Count -ne 1 -or
        $dailyDownloads[0].day -ne "2026-01-02" -or
        $dailyDownloads[0].package -ne "math_extra@0.1.0" -or
        $dailyDownloads[0].count -ne 3 -or
        $analyticsReport.last_publish.name -ne "math_extra") {
        throw "expected registry analytics --json to include top and daily package metrics"
    }

    $health = Run-Pkg -PkgArgs @("registry-health", $registry, "--json")
    if ($health.Code -ne 0) {
        Write-Output $health.Output
        throw "expected local registry-health --json to pass"
    }
    $healthReport = $health.Output | ConvertFrom-Json
    if ($healthReport.schema -ne "sura.registry.health.v1" -or
        $healthReport.source -ne "local" -or
        $healthReport.passed -ne $true -or
        $healthReport.package_count -ne 1 -or
        $healthReport.stats_present -ne $true -or
        $healthReport.advisory_count -ne 1 -or
        $healthReport.active_advisory_count -ne 1 -or
        $healthReport.error_count -ne 0 -or
        -not ($healthReport.checks | Where-Object { $_.name -eq "index" -and $_.status -eq "ok" })) {
        $healthReport | ConvertTo-Json -Depth 6
        throw "expected local registry-health --json to summarize package, stats, and advisory state"
    }

    $healthWarningGate = Run-Pkg -PkgArgs @("registry-health", $registry, "--fail-on-warning", "--json")
    if ($healthWarningGate.Code -eq 0) {
        Write-Output $healthWarningGate.Output
        throw "expected local registry-health --fail-on-warning --json to fail on warnings"
    }
    $healthWarningReport = $healthWarningGate.Output | ConvertFrom-Json
    if ($healthWarningReport.schema -ne "sura.registry.health.v1" -or
        $healthWarningReport.source -ne "local" -or
        $healthWarningReport.passed -ne $false -or
        $healthWarningReport.fail_on_warning -ne $true -or
        $healthWarningReport.error_count -ne 0 -or
        $healthWarningReport.warning_count -lt 1) {
        $healthWarningReport | ConvertTo-Json -Depth 6
        throw "expected local registry-health --fail-on-warning JSON gate report"
    }

    "registry_client_smoke: PASS"
}
finally {
    $env:SURA_REGISTRY = $oldRegistry
    $env:SURA_REGISTRY_URL = $oldRegistryUrl
    if (Test-Path $temp) {
        Remove-Item -LiteralPath $temp -Recurse -Force
    }
}
